// Equivalence test for the "ansible" recipe (src/recipes/ansible.ts): for each
// of the three ansible-* examples, the declarative build.yml pipeline
// (loadBuildSpec -> assembleFromSpecWithReport) must reproduce the example's
// committed input.json — which is what the hand-written build.ts produced
// before the recipe layer replaced it.
//
// The examples' input.json is git-ignored and regenerated by
// `cd examples/<n> && bun run ../../src/cli.ts import --spec review-sheet/build.yml -o input.json`,
// so it reflects the current source files rather than a stale snapshot; run
// that for each example before this test if the sources changed.
//
// Path convention note: `resolve` here returns paths relative to the example's
// own root (e.g. "roles/keycloak/defaults/main.yml") rather than the CLI's
// CWD-relative one — both are legitimate; this one is what makes a
// byte-for-byte comparison against the committed input.json possible.
// `readFile` accepts either form (root-relative from the recipe, or absolute
// from loadBuildSpec's own project/metadata_dirs/argument_specs resolution).

import { describe, it, expect, beforeEach } from "bun:test";
import { stubNonBuiltInProviders } from "./only-builtin-providers.js";
import { readFileSync } from "node:fs";
import { resolve as resolvePath, relative as relativePath, join, isAbsolute } from "node:path";
import { loadBuildSpec } from "../src/spec";
import "../src/recipes/index";
import { getRecipe, type RecipeIO } from "../src/recipe";
import { assembleFromSpecWithReport } from "../src/assemble-spec";
import { assembleSheets } from "../src/assemble";
import type { Parameter } from "../src/types";
import type { ValueLayer } from "../src/assemble";

// The metadata provider registry is a process-wide singleton (see
// assemble.test.ts / spec.test.ts for the full rationale) — neutralize any
// non-core provider before each test so enrich()'s dictionary/argument-specs/
// project counts don't depend on cross-file test execution order.
beforeEach(stubNonBuiltInProviders);

const REPO_ROOT = resolvePath(__dirname, "..");

function makeReadFile(exampleRoot: string): (path: string) => string | null {
  return (p: string): string | null => {
    const abs = isAbsolute(p) ? p : join(exampleRoot, p);
    try {
      return readFileSync(abs, "utf-8");
    } catch {
      return null;
    }
  };
}

function buildActual(exampleName: string): ReturnType<typeof assembleFromSpecWithReport> {
  const exampleRoot = join(REPO_ROOT, "examples", exampleName);
  const specDir = join(exampleRoot, "review-sheet");
  const readFile = makeReadFile(exampleRoot);

  // Deliberately the exported library path (assemble-spec.ts), i.e. exactly
  // what `import --spec` runs — re-assembling the pipeline by hand here once
  // let a spec field (materialize) reach the CLI but not this test.
  return assembleFromSpecWithReport(loadBuildSpec(join(specDir, "build.yml"), { readFile }), {
    readFile,
    specDir,
    resolve: (p: string) => relativePath(exampleRoot, resolvePath(specDir, p)),
  });
}

function loadExpected(exampleName: string): unknown {
  const exampleRoot = join(REPO_ROOT, "examples", exampleName);
  return JSON.parse(readFileSync(join(exampleRoot, "input.json"), "utf-8"));
}

// A JSON round-trip normalizes both sides the same way (drops `undefined`
// properties, etc.) before the structural comparison.
function jsonRoundTrip(v: unknown): unknown {
  return JSON.parse(JSON.stringify(v));
}

function stripGeneratedAt(doc: unknown): unknown {
  const d = doc as { metadata?: { generated_at?: string }; artifacts?: unknown };
  if (d.metadata) delete d.metadata.generated_at;
  // `artifacts` too. These tests assert that the declarative recipe produces
  // the same MODEL as the hand-written converter each example shipped with, and
  // an artifact preview is not part of that model: it is display context (the
  // whole deployed file, rendered), which a hand-written converter never
  // emitted and which carries no row, no value and no review target. Comparing
  // it here would only ever assert that the expectation file was regenerated.
  // The previews have their own test — tests/artifact-preview.test.ts, against
  // a committed rendered artifact, which is a stronger check than equality with
  // a snapshot of themselves.
  delete d.artifacts;
  return doc;
}

type CategoryLike = { params?: Parameter[]; categories?: CategoryLike[] };

// Materialized rows are filed two levels deep — a parent "defaults" category,
// then a subcategory per dictionary group (see fileDrafts in assemble.ts) —
// so this recurses through `categories` instead of reading only the top level.
function paramsOf(cat: CategoryLike): Parameter[] {
  return [...(cat.params ?? []), ...(cat.categories ?? []).flatMap(paramsOf)];
}

function allParams(doc: unknown): Parameter[] {
  const d = doc as { sheets: { categories: CategoryLike[] }[] };
  return d.sheets.flatMap((s) => s.categories.flatMap(paramsOf));
}

function originCounts(params: Parameter[]): { common: number; overlay: number; embedded: number; default: number; out_of_scope: number } {
  const counts = { common: 0, overlay: 0, embedded: 0, default: 0, out_of_scope: 0 };
  for (const p of params) {
    if (p.origin === "common") counts.common++;
    else if (p.origin === "overlay") counts.overlay++;
    else if (p.origin === "embedded") counts.embedded++;
    else if (p.origin === "default") counts.default++;
    if (p.out_of_scope) counts.out_of_scope++;
  }
  return counts;
}

describe("ansible recipe: equivalence with the hand-written build.ts examples", () => {
  it("ansible-basic: nginx + postgresql", () => {
    const { input, report } = buildActual("ansible-basic");
    const actual = stripGeneratedAt(jsonRoundTrip(input));
    const expected = stripGeneratedAt(loadExpected("ansible-basic"));
    expect(actual).toEqual(expected);

    // 384 = 44 project-set params + 340 materialized default rows, every one of
    // the latter documented straight from the dictionary (which is what keeps
    // strict metadata passing for a full inventory nobody hand-authored). The
    // 341st is krb_server_keyfile, which sheet.yml marks out_of_scope — exempt
    // from enrichment as well as from strict.
    expect(report.filled).toBe(384);
    // project:9 is category placement, two remarks, and one out_of_scope.
    // pg_max_connections/pg_shared_buffers no longer need a project-metadata
    // override: the argument-specs provider now falls back from a row's
    // renamed key (max_connections/shared_buffers, the pg_settings directive)
    // to its ORIGINAL variable name (pg_max_connections/pg_shared_buffers)
    // when the key alone doesn't match (see providers/argument-specs.ts's
    // query.key-then-query.variable fallback, and metadata.ts's
    // MetadataQuery.variable) — S2's rename no longer strands that entry.
    // argument-specs:4 = the two descriptions (en) plus the two `type` fields
    // it also carries. Every other description still comes straight from the
    // nginx/postgresql dictionaries, so another project reviewing the same
    // products inherits them.
    expect(report.byProvider).toEqual({ dictionary: 1185, project: 9, "argument-specs": 4 });

    const counts = originCounts(allParams(actual));
    // 341 "default" rows: the postgresql sheet materializes pg_settings, so it
    // is the full inventory (22 set knobs + everything left at its default).
    expect(counts).toEqual({ common: 12, overlay: 16, embedded: 16, default: 341, out_of_scope: 1 });
  });

  it("ansible-httpd: httpd", () => {
    const { input, report } = buildActual("ansible-httpd");
    const actual = stripGeneratedAt(jsonRoundTrip(input));
    const expected = stripGeneratedAt(loadExpected("ansible-httpd"));
    expect(actual).toEqual(expected);

    // 19 = 18 + IfModule: httpd.ts now extracts <IfModule mpm_event_module>'s
    // module test as its own row (source = the opening tag), so it needs a
    // category and a description like every other directive here — both come
    // from the httpd@2.4 dictionary.
    expect(report.filled).toBe(19);
    // S2: every row is now named after its Apache directive (ServerTokens,
    // MaxRequestWorkers, ...), so meta/argument_specs.yml — which documents
    // httpd_server_tokens/httpd_max_request_workers by VARIABLE name — no
    // longer matches either row by `query.key` alone, but the provider falls
    // back to the row's ORIGINAL variable name (see providers/
    // argument-specs.ts's query.key-then-query.variable fallback), so it
    // still reaches both. project:1 is back down to just Include's category
    // placement (the two ServerTokens/MaxRequestWorkers description overrides
    // that used to live in sheet.yml are gone — argument_specs.yml is
    // reachable again, so nothing needed restating).
    expect(report.byProvider).toEqual({ dictionary: 91, project: 1, "argument-specs": 4 });

    const counts = originCounts(allParams(actual));
    // embedded: 3 = 2 + IfModule (a literal test in the template, like
    // Include/TypesConfig — not an Ansible variable).
    expect(counts).toEqual({ common: 10, overlay: 6, embedded: 3, default: 0, out_of_scope: 0 });
  });

  it("ansible-keycloak: server config + realm + clients, three sheets off one role", () => {
    const { input, report } = buildActual("ansible-keycloak");
    const actual = stripGeneratedAt(jsonRoundTrip(input));
    const expected = stripGeneratedAt(loadExpected("ansible-keycloak"));
    expect(actual).toEqual(expected);

    // 278 = the server sheet's 138 (18 keys the role sets + 121 materialized
    // rows, of 239 candidates — 118 carry no documented `default` and are
    // excluded by assemble.ts's materialize no-default gate — minus the one
    // the project marks out_of_scope, exempt from enrichment as from strict)
    // plus the realm sheet's 112 (25 the role sets + 87 materialized, of 150
    // candidates) and the clients sheet's 28.
    expect(report.filled).toBe(278);
    // project:10 is every row Keycloak's admin console declines to name on its
    // own: the realm's four (each edited through a control writing SEVERAL
    // fields at once, so the extractor attributes that control's help text to
    // none of them) and the clients' equivalent, plus the `enabled` literals
    // the console shows as a header toggle rather than a form field, plus
    // `ifResourceExists`, which is a partial-import directive and not a
    // ClientRepresentation field at all. Everything else — all three sheets —
    // comes from the three extracted dictionaries.
    expect(report.byProvider).toEqual({ dictionary: 1059, project: 10 });

    const server = input.sheets.find((s) => s.name === "keycloak configuration");
    const realm = input.sheets.find((s) => s.name === "keycloak realm");
    const clients = input.sheets.find((s) => s.name === "keycloak clients");
    expect(server && realm && clients).toBeTruthy();

    // The server dictionary is a real full extraction and the sheet is keyed by
    // the product's own config keys, so materializing (minus the no-default
    // exclusion above) makes it the exhaustive ledger of what Keycloak can be
    // configured with AND documented a real default for.
    expect(originCounts(allParams({ sheets: [server] }))).toEqual({
      common: 10,
      overlay: 7,
      embedded: 1,
      default: 121,
      out_of_scope: 1,
    });
    // The realm sheet materializes too, which it could not do until the
    // extractor stopped losing the console's own words: 47 fields had a product
    // default and no product wording, the strict gate refused them, and the
    // count is now 13 — all of them in the dictionary's community overlay,
    // each with a recorded reason why the product says nothing. 87 of the 150
    // candidate fields carry a documented default; the rest have none and the
    // no-default gate excludes them. See build.yml.
    expect(originCounts(allParams({ sheets: [realm] }))).toEqual({
      common: 14,
      overlay: 10,
      embedded: 1,
      default: 87,
      out_of_scope: 0,
    });
    // Clients are a third sheet, not more rows on the realm one: five field
    // names exist in both RealmRepresentation and ClientRepresentation, so a
    // single sheet binding both dictionaries would make each of them
    // ambiguous. embedded: 3 = the two `protocol` literals (what makes each
    // client the thing it is) plus `ifResourceExists`.
    expect(originCounts(allParams({ sheets: [clients] }))).toEqual({
      common: 15,
      overlay: 10,
      embedded: 3,
      default: 0,
      out_of_scope: 0,
    });
  });
});

// The sheet's two paths: where the configuration LANDS (what an operator
// reviewing middleware parameters looks for) and the local file it is generated
// from (what verify/apply must act on). See src/types.ts's Sheet.file_path /
// source_file — the convention this recipe used backwards until now.
describe("ansible recipe: deployed_path", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": "nginx_port: 80\n",
    "/r/nginx.conf.j2": "listen {{ nginx_port }};\nsendfile on;\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: [],
  };
  const load = (extra: Record<string, string> = {}) => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "nginx", recipe: "ansible", defaults: "defaults.yml", template: "nginx.conf.j2", ...extra },
      io
    );
  };

  it("shows the deployed path and keeps the template as the source", () => {
    const si = load({ deployed_path: "/etc/nginx/nginx.conf" });
    expect(si.filePath).toBe("/etc/nginx/nginx.conf"); // verbatim: a path over there, not in the repo
    expect(si.sourceFile).toBe("/r/nginx.conf.j2");
  });

  it("falls back to the template as the displayed path when none is declared", () => {
    const si = load();
    expect(si.filePath).toBe("/r/nginx.conf.j2");
    expect(si.sourceFile).toBeUndefined();
  });

  it("refuses a deployed path with no template to render", () => {
    const recipe = getRecipe("ansible")!;
    expect(() =>
      recipe.load(
        { name: "nginx", recipe: "ansible", defaults: "defaults.yml", deployed_path: "/etc/nginx/nginx.conf" },
        io
      )
    ).toThrow(/no template/);
  });
});

// One group_vars file per host group, holding the variables of every role
// applied to it, is the ordinary Ansible layout — so a sheet built from ONE
// role's defaults sees the other roles' variables in its overlays and files
// them as its own parameters. The PoC hand-wrote 8 `out_of_scope` entries to
// suppress that, boilerplate growing with the number of sheets.
describe("ansible recipe: include/exclude key filters", () => {
  const files: Record<string, string> = {
    // The role's own defaults.
    "/r/defaults.yml": "httpd_port: 80\nhttpd_log_level: warn\n",
    // Shared group_vars: this role's variables plus two other roles'.
    "/r/group_vars.yml": "httpd_port: 8080\nkc_db_url: jdbc:postgresql://db/kc\nkcr_env: staging\nhttpd_only_here: on\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: ["staging"],
  };
  const load = (extra: Record<string, unknown> = {}) => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", overlays: { staging: "group_vars.yml" }, ...extra } as never,
      io
    );
  };
  const overlayKeys = (si: ReturnType<typeof load>) =>
    [...(si.layers.find((l) => l.kind === "overlay")!.entries.keys())];

  it("takes every overlay key by default — the behaviour a filter is opting out of", () => {
    expect(overlayKeys(load()).sort()).toEqual(["httpd_only_here", "httpd_port", "kc_db_url", "kcr_env"]);
  });

  it("drops the other roles' variables with exclude", () => {
    expect(overlayKeys(load({ exclude: ["kc_*", "kcr_*"] })).sort()).toEqual(["httpd_only_here", "httpd_port"]);
  });

  it("keeps only this role's variables with include", () => {
    expect(overlayKeys(load({ include: ["httpd_*"] })).sort()).toEqual(["httpd_only_here", "httpd_port"]);
  });

  it("keeps an overlay-only key that matches — a per-environment variable with no default is a legitimate row", () => {
    expect(overlayKeys(load({ include: ["httpd_*"] }))).toContain("httpd_only_here");
  });

  it("applies to the base layer too, so a filtered key is gone from the sheet entirely", () => {
    const si = load({ include: ["httpd_port"] });
    const base = si.layers.find((l) => l.kind === "base")!;
    expect([...base.entries.keys()]).toEqual(["httpd_port"]);
  });

  it("warns about a pattern that matched nothing", () => {
    const warnings: string[] = [];
    const original = console.warn;
    console.warn = (m: string) => warnings.push(m);
    try {
      load({ exclude: ["nope_*"] });
    } finally {
      console.warn = original;
    }
    expect(warnings.join("\n")).toContain("nope_*");
  });
});

// S1: a template variable that backs more than one directive (httpd's
// ProxyPass/ProxyPassReverse pair, both driven by the same backend variable)
// has no single product key to legitimately be — the observed bug was the
// LAST directive silently winning the row's name, dropping the other
// directive with no trace. See ansible.ts's module doc for the fix. S2: this
// derivation now runs for every templated sheet automatically, no `keying`
// flag to opt into it.
describe("ansible recipe: a variable used by more than one directive in the template", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": [
      "httpd_health_backend: http://127.0.0.1:9000",
      "httpd_proxy_backend: http://127.0.0.1:8080",
    ].join("\n"),
    // basename "httpd.conf" (after the .j2 strip) is unconditionally detected
    // as httpd by isHttpd(), so this needs no <Tag> block to be recognized.
    "/r/httpd.conf.j2": [
      'ProxyPass        "/health" "{{ httpd_health_backend }}/health"',
      'ProxyPassReverse "/health" "{{ httpd_health_backend }}/health"',
      'ProxyPass        "/"       "{{ httpd_proxy_backend }}/"',
      'ProxyPassReverse "/"       "{{ httpd_proxy_backend }}/"',
    ].join("\n"),
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: [],
  };
  const load = () => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", template: "httpd.conf.j2" },
      io
    );
  };

  it("files the N>1 variable under its own name, not the last directive it happened to touch", () => {
    const si = load();
    const base = si.layers.find((l): l is Extract<typeof si.layers[number], { kind: "base" }> => l.kind === "base")!;
    // httpd_health_backend backs both ProxyPass[0] and ProxyPassReverse[0] — no
    // single product key — so it must be keyed by the variable name itself,
    // never by either directive's key.
    expect(base.entries.has("httpd_health_backend")).toBe(true);
    expect(base.entries.has("ProxyPass[0]")).toBe(false);
    expect(base.entries.has("ProxyPassReverse[0]")).toBe(false);
    // httpd_proxy_backend is the same story for the second pair.
    expect(base.entries.has("httpd_proxy_backend")).toBe(true);
    expect(base.entries.has("ProxyPass[1]")).toBe(false);
    expect(base.entries.has("ProxyPassReverse[1]")).toBe(false);
  });

  it("does not add N>1 variables to keyMap — resolveKey's own fallback is what names the row after the variable", () => {
    const si = load();
    // No variable in this fixture backs exactly one directive, so keyMap ends
    // up empty and is omitted entirely (see ansible.ts) rather than kept as [].
    expect(si.keyMap).toBeUndefined();
  });

  it("reports every N>1 variable — never decides silently", () => {
    const warnings: string[] = [];
    const original = console.warn;
    console.warn = (m: string) => warnings.push(m);
    try {
      load();
    } finally {
      console.warn = original;
    }
    const joined = warnings.join("\n");
    expect(joined).toContain("httpd_health_backend");
    expect(joined).toContain("ProxyPass[0]");
    expect(joined).toContain("ProxyPassReverse[0]");
    expect(joined).toContain("httpd_proxy_backend");
    expect(joined).toContain("ProxyPass[1]");
    expect(joined).toContain("ProxyPassReverse[1]");
  });

  it("still keys a 1:1 variable by its product (directive) key as before", () => {
    const files1to1: Record<string, string> = {
      "/r/defaults.yml": "httpd_port: 8080\n",
      "/r/httpd.conf.j2": 'Listen "{{ httpd_port }}"\n',
    };
    const io1to1: RecipeIO = {
      readFile: (p: string) => files1to1[p] ?? null,
      specDir: "/r",
      resolve: (p: string) => `/r/${p.split("/").pop()}`,
      instances: [],
    };
    const recipe = getRecipe("ansible")!;
    const si = recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", template: "httpd.conf.j2" },
      io1to1
    );
    expect(si.keyMap).toEqual([{ boundKey: "Listen", variable: "httpd_port" }]);
  });
});

// S2: a `defaults` variable the template never resolves into a row (never
// referenced, or only tested in a Jinja `{% if %}`, like nginx's own
// nginx_gzip) must not be silently dropped just because "keying: bound" no
// longer exists to route it through the old "source"-only fallback. But it
// must only be RESCUED into the base map when it would otherwise be entirely
// invisible — a variable some overlay DOES set is already recovered by
// assemble.ts's own "keys seen only in overlays" sweep, with its true
// historical shape (a Pattern B row covering only the instances that set
// it); rescuing it here too would additionally fabricate a base value for
// every instance that never set it — a real behavior change, observed in the
// PoC's keycloak sheet (kc_bootstrap_admin_username/password, set only on
// `local`) before this distinction was added.
describe("ansible recipe: a defaults variable the template never resolves into a row", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": ["httpd_port: 8080", "httpd_gzip: true", "httpd_extra: fallback"].join("\n"),
    "/r/httpd.conf.j2": ['Listen "{{ httpd_port }}"', "{% if httpd_gzip %}", "gzip on;", "{% endif %}"].join("\n"),
    "/r/overlay.yml": "httpd_extra: staging-value\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: ["staging"],
  };
  const load = () => {
    const recipe = getRecipe("ansible")!;
    return recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", template: "httpd.conf.j2", overlays: { staging: "overlay.yml" } },
      io
    );
  };

  it("rescues a variable no overlay ever sets into the base map, under its own name", () => {
    const si = load();
    const base = si.layers.find((l): l is Extract<typeof si.layers[number], { kind: "base" }> => l.kind === "base")!;
    expect(base.entries.has("httpd_gzip")).toBe(true);
    expect(base.entries.get("httpd_gzip")?.value).toBe("true");
  });

  it("does NOT rescue a variable some overlay sets — leaves it out of the base map entirely", () => {
    const si = load();
    const base = si.layers.find((l): l is Extract<typeof si.layers[number], { kind: "base" }> => l.kind === "base")!;
    // Left for assemble.ts's own overlay-only sweep to recover — see
    // buildDrafts in assemble.ts, which the equivalence test (assemble.test.ts)
    // covers for the resulting Pattern B shape.
    expect(base.entries.has("httpd_extra")).toBe(false);
  });
});

// `templates:` — one sheet covering several deployed artifacts, because the
// incumbent Excel sheet covers them together and acceptance review compares the
// two side by side. Each template becomes a component; without that, two units
// that both have Unit.Description would collide on one row key and the later
// one would silently win.
describe("ansible recipe: several templates on one sheet", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": ["app_db_url: jdbc:postgresql://db/app", "app_log_level: info"].join("\n"),
    // Two systemd units. Both declare Description — the collision this exists for.
    "/r/keycloak.service.j2": [
      "[Unit]",
      "Description=Keycloak",
      "[Service]",
      "Environment=APP_DB_URL={{ app_db_url }}",
      "Restart=on-failure",
    ].join("\n"),
    "/r/keycloak-secrets.service.j2": ["[Unit]", "Description=Fetch the DB password", "[Service]", "Type=oneshot"].join(
      "\n"
    ),
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: [],
  };
  const load = (spec: Record<string, unknown>) => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load({ name: "keycloak", recipe: "ansible", defaults: "defaults.yml", ...spec } as never, io);
  };

  const twoTemplates = {
    templates: [
      { path: "keycloak.service.j2", deployed_path: "/etc/systemd/system/keycloak.service" },
      { path: "keycloak-secrets.service.j2", deployed_path: "/etc/systemd/system/keycloak-secrets.service" },
    ],
  };

  it("keeps a row key that both templates use, one per component", () => {
    const si = load(twoTemplates);
    const descriptions = si.embedded.filter((e) => e.key === "Unit.Description");

    expect(descriptions).toHaveLength(2);
    expect(descriptions.map((e) => e.component).sort()).toEqual([
      "keycloak-secrets.service",
      "keycloak.service",
    ]);
    expect(descriptions.map((e) => e.value).sort()).toEqual(["Fetch the DB password", "Keycloak"]);
  });

  it("names each component after its artifact, not its template file", () => {
    const si = load(twoTemplates);
    // keycloak.service.j2 -> keycloak.service: what a reviewer calls the file
    // that lands on the host, with the templating suffix gone.
    expect([...(si.componentLabels?.keys() ?? [])].sort()).toEqual([
      "keycloak-secrets.service",
      "keycloak.service",
    ]);
  });

  it("records each literal against the template it came from", () => {
    const si = load(twoTemplates);
    const restart = si.embedded.find((e) => e.key === "Service.Restart");
    const type = si.embedded.find((e) => e.key === "Service.Type");

    expect(restart?.component).toBe("keycloak.service");
    expect(restart?.source.file).toBe("/r/keycloak.service.j2");
    expect(type?.component).toBe("keycloak-secrets.service");
    expect(type?.source.file).toBe("/r/keycloak-secrets.service.j2");
  });

  it("still resolves a {{ var }} against defaults, and scopes it to its template", () => {
    const si = load(twoTemplates);
    const base = si.layers.find((l) => l.kind === "base") as Extract<ValueLayer, { kind: "base" }>;

    // The variable keeps its own name as the layer key, so an overlay in
    // group_vars still finds it — that lookup is by the extracted key.
    expect(base.entries.get("app_db_url")?.value).toBe("jdbc:postgresql://db/app");
    expect(si.keyMap).toContainEqual({ boundKey: "Service.Environment", variable: "app_db_url" });
    expect(si.componentOf?.get("app_db_url")).toBe("keycloak.service");
  });

  it("leaves a variable shared by two templates out of every component", () => {
    const shared: Record<string, string> = {
      ...files,
      "/r/a.conf.j2": "log-level={{ app_log_level }}",
      "/r/b.conf.j2": "loglevel={{ app_log_level }}",
    };
    const sharedIo: RecipeIO = { ...io, readFile: (p: string) => shared[p] ?? null };
    const recipe = getRecipe("ansible")!;
    const si = recipe.load(
      {
        name: "kc",
        recipe: "ansible",
        defaults: "defaults.yml",
        templates: [{ path: "a.conf.j2" }, { path: "b.conf.j2" }],
      } as never,
      sharedIo
    );

    // It genuinely belongs to both files. Claiming one would be a guess, and
    // the row is honest sitting outside every component heading.
    expect(si.componentOf?.get("app_log_level")).toBeUndefined();
    // And it earns no product key either — the existing not-1:1 rule, now
    // counted across the whole sheet rather than within one template.
    expect(si.keyMap?.some((m) => m.variable === "app_log_level")).toBeFalsy();
  });

  it("rejects declaring both template and templates", () => {
    expect(() => load({ template: "keycloak.service.j2", ...twoTemplates })).toThrow(/both "template" and "templates"/);
  });

  it("rejects a sheet-wide deployed_path alongside templates", () => {
    expect(() => load({ ...twoTemplates, deployed_path: "/etc/somewhere" })).toThrow(/declare deployed_path inside each entry/);
  });

  it("leaves a single `template:` sheet with no component at all", () => {
    // A sheet that IS one artifact needs no level naming it above every
    // category — the collapse rule in assemble.ts would drop it anyway, but not
    // creating it keeps the row keys where they were.
    const si = load({ template: "keycloak.service.j2", deployed_path: "/etc/systemd/system/keycloak.service" });

    expect(si.componentOf).toBeUndefined();
    expect(si.componentLabels).toBeUndefined();
    expect(si.filePath).toBe("/etc/systemd/system/keycloak.service");
  });
});

// A template line built from SEVERAL variables.
//
// `source.templateVar` is the parser's answer to "which variable IS this
// value", and it takes the first one — a claim a mixed line cannot keep. On
// `db-url=jdbc:…{{ db_host }}:5432/{{ db_name }}` it named db_host and said
// nothing about db_name, so the recipe saw a 1:1 line whose second variable the
// template never mentions. Two things followed: db_host was renamed after the
// directive, giving a row that reads `db-url = db.internal`, and db_name was
// rescued as an unreferenced default and filed under the variable FILE.
describe("ansible recipe: a line built from several variables", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": "app_port: 8080\ndb_host: db.internal\ndb_name: appdb\n",
    "/r/app.conf.j2": "port={{ app_port }}\ndb-url=jdbc:postgresql://{{ db_host }}:5432/{{ db_name }}\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: [],
  };
  const load = () => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "app", recipe: "ansible", defaults: "defaults.yml", template: "app.conf.j2", deployed_path: "/etc/app/app.conf" },
      io
    );
  };

  it("names no variable after the directive they jointly build", () => {
    // Either choice would produce a row carrying the directive's name and one
    // variable's value — the same misrepresentation the mirror case (one
    // variable driving several directives) is already refused for.
    const si = load();
    expect(si.keyMap?.map((k) => k.boundKey)).not.toContain("db-url");
  });

  it("still names the 1:1 line's variable after its directive", () => {
    const si = load();
    expect(si.keyMap).toContainEqual({ boundKey: "port", variable: "app_port" });
  });

  it("reports every variable the artifact interpolates, not just the first", () => {
    // What `group_by: file` needs in order to know these rows are lines of the
    // artifact. Taken from keyMap it could not know: that table is empty
    // exactly where the relationship is not 1:1.
    const si = load();
    expect([...(si.templateVariables ?? [])].sort()).toEqual(["app_port", "db_host", "db_name"]);
  });
});

// The other half, at the assembler: where those rows are FILED under
// `group_by: file`. A row whose value came from a variable the artifact
// interpolates is a line of that artifact — the variable is provenance, shown
// in the under_key column, and filing by it splits one file's settings across
// two headings for a reason about how the file is built.
describe("group_by: file with a multi-variable line", () => {
  it("files every variable of the line under the artifact, not the variable file", () => {
    const recipe = getRecipe("ansible")!;
    const files: Record<string, string> = {
      "/r/defaults.yml": "app_port: 8080\ndb_host: db.internal\ndb_name: appdb\n",
      "/r/app.conf.j2": "port={{ app_port }}\ndb-url=jdbc:postgresql://{{ db_host }}:5432/{{ db_name }}\n",
      "project.yml":
        "sheets:\n  app:\n    under_key: { id: variable, label: { en: V } }\n" +
        "    params:\n      port: { description: { en: p } }\n      db_host: { description: { en: h } }\n" +
        "      db_name: { description: { en: n } }\n",
    };
    const si = recipe.load(
      { name: "app", recipe: "ansible", defaults: "defaults.yml", template: "app.conf.j2", deployed_path: "/etc/app/app.conf" },
      {
        readFile: (p: string) => files[p] ?? null,
        specDir: "/r",
        resolve: (p: string) => `/r/${p.split("/").pop()}`,
        instances: [],
      }
    );
    const input = assembleSheets([si], {
      projectPath: "project.yml",
      readFile: (p: string) => files[p] ?? null,
      strictMetadata: false,
    });
    const cats = input.sheets[0].categories.map((c) => c.name);
    // One heading, the artifact's — named in full, because an absolute path is
    // where the file LANDS and that is what a reviewer is holding.
    // `defaults.yml` appearing beside it — holding exactly the one variable the
    // first-variable rule could not see — is the bug this is here for.
    expect(cats).toEqual(["/etc/app/app.conf"]);
    expect((input.sheets[0].categories[0].params ?? []).map((p) => p.key).sort()).toEqual([
      "db_host",
      "db_name",
      "port",
    ]);
  });

  // The same line on the ARTIFACT axis, which is where the fix above did not
  // reach. There a row is named after the DIRECTIVE (`db-url`), and the set the
  // check consulted holds VARIABLE names — a question in the wrong namespace,
  // always false. So the row fell out of the artifact it is a line of and
  // opened a category named after the file its variables are DEFINED in, one
  // row wide, beside the file it belongs to.
  it("keeps a multi-variable DIRECTIVE in the artifact, not in the variables' file", () => {
    const recipe = getRecipe("ansible")!;
    const files: Record<string, string> = {
      "/r/defaults.yml": "app_port: 8080\ndb_host: db.internal\ndb_name: appdb\n",
      "/r/app.conf.j2": "port={{ app_port }}\ndb-url=jdbc:postgresql://{{ db_host }}:5432/{{ db_name }}\n",
      "project.yml":
        "sheets:\n  app:\n    under_key: { id: variable, label: { en: V } }\n" +
        "    params:\n      port: { description: { en: p } }\n      db-url: { description: { en: u } }\n",
    };
    const si = recipe.load(
      {
        name: "app",
        recipe: "ansible",
        rows: "artifact",
        defaults: "defaults.yml",
        template: "app.conf.j2",
        deployed_path: "/etc/app/app.conf",
      },
      {
        readFile: (p: string) => files[p] ?? null,
        specDir: "/r",
        resolve: (p: string) => `/r/${p.split("/").pop()}`,
        instances: [],
      }
    );
    const input = assembleSheets([si], {
      projectPath: "project.yml",
      readFile: (p: string) => files[p] ?? null,
      strictMetadata: false,
    });
    // One heading. `defaults.yml` beside it, holding only `db-url`, is the bug.
    expect(input.sheets[0].categories.map((c) => c.name)).toEqual(["/etc/app/app.conf"]);
    expect((input.sheets[0].categories[0].params ?? []).map((p) => p.key).sort()).toEqual(["db-url", "port"]);
  });

  // The recipe has to SAY which rows those are: the model could not answer it,
  // and the set that looked like it could is in the other namespace.
  it("reports the row keys a variable was interpolated into", () => {
    const recipe = getRecipe("ansible")!;
    const files: Record<string, string> = {
      "/r/defaults.yml": "db_host: db.internal\ndb_name: appdb\n",
      "/r/app.conf.j2": "db-url=jdbc:postgresql://{{ db_host }}:5432/{{ db_name }}\n",
    };
    const si = recipe.load(
      { name: "app", recipe: "ansible", rows: "artifact", defaults: "defaults.yml", template: "app.conf.j2" },
      {
        readFile: (p: string) => files[p] ?? null,
        specDir: "/r",
        resolve: (p: string) => `/r/${p.split("/").pop()}`,
        instances: [],
      }
    );
    expect(si.variableBackedKeys).toEqual(["db-url"]);
    // ...and the variable names stay in their own list, which is what the
    // variable axis reads.
    expect([...(si.templateVariables ?? [])].sort()).toEqual(["db_host", "db_name"]);
  });
});


// What a part is answerable for. `defaults:` names a file, and every variable in
// it that no template resolves into a row becomes a row of its own — this
// project never drops one silently. That is right when the variable IS part of
// the deliverable and simply has no file to be a line of (a state a command
// applies), and wrong when the file was a role-wide one shared with other
// sheets. The tool cannot tell those apart; it can refuse to be silent about
// which case it is in, and it can stop demanding the file when nothing needs it.
describe("ansible recipe: the defaults a part is given", () => {
  const FILES: Record<string, string> = {
    "/vars.yml": "unused_a: 1\nunused_b: two\n",
    // A fixed-value policy: no `{{ … }}` anywhere in it.
    "/policy.j2": "/var/log/app.log {\n    daily\n    rotate 7\n}\n",
  };
  const io = { readFile: (p: string) => FILES[p] ?? null, specDir: "/", resolve: (p: string) => p, instances: [] };
  const load = (spec: Record<string, unknown>) => {
    const warnings: string[] = [];
    const orig = console.warn;
    console.warn = (...a: unknown[]) => void warnings.push(String(a[0]));
    try {
      const si = getRecipe("ansible")!.load(
        {
          name: "s",
          recipe: "ansible",
          rows: "artifact",
          templates: [{ path: "/policy.j2", component: "/etc/logrotate.d/app", deployed_path: "/etc/logrotate.d/app" }],
          ...spec,
        } as never,
        io as never
      );
      const base = si.layers.find((l) => l.kind === "base") as { entries: Map<string, unknown> } | undefined;
      return { keys: [...(base?.entries.keys() ?? [])], warnings };
    } finally {
      console.warn = orig;
    }
  };

  // The case that raised this: a template with no variables in it had to name a
  // vars file anyway, and naming one made the part answerable for all of it.
  it("does not require defaults, and reviews only the templates without one", () => {
    const { keys, warnings } = load({});
    expect(keys).toEqual([]);
    expect(warnings).toEqual([]);
  });

  it("still files an unreferenced variable as a row, and says it did", () => {
    const { keys, warnings } = load({ defaults: "/vars.yml" });
    expect(keys).toEqual(["unused_a", "unused_b"]);
    const said = warnings.find((w) => w.includes("named by no template"));
    expect(said).toBeDefined();
    expect(said).toContain("unused_a");
    expect(said).toContain("include:/exclude:");
  });

  // A variable an `include:` admits is one the author asked for. A sheet
  // reviewing something no file carries — a state a command applies — is what
  // that declaration is for, and warning there tells an author their own
  // decision is a mistake.
  it("says nothing when the sheet declared what it reads", () => {
    const { keys, warnings } = load({ defaults: "/vars.yml", include: ["unused_a"] });
    expect(keys).toEqual(["unused_a"]);
    expect(warnings.filter((w) => w.includes("named by no template"))).toEqual([]);
  });
});


// `instances` says WHERE a row is; this says WHY. A block that exists in
// production and not in dev is read by asking what turned it on, and until now
// that answer lived only on the struck-through line of the preview panel — a
// place you reach by knowing to look.
describe("ansible recipe: why a row is in some environments and not others", () => {
  const FILES: Record<string, string> = {
    "/vars.yml": "some_flag: false\nport: 8080\n",
    "/prod.yml": "some_flag: true\n",
    "/app.conf.j2": "Listen {{ port }}\n{% if some_flag %}\nExtra on\n{% endif %}\n",
  };
  const io = { readFile: (p: string) => FILES[p] ?? null, specDir: "/", resolve: (p: string) => p, instances: ["dev", "prod"] };
  const rows = (files = FILES) => {
    const si = getRecipe("ansible")!.load(
      {
        name: "s",
        recipe: "ansible",
        rows: "artifact",
        defaults: "/vars.yml",
        overlays: { dev: "/dev.yml", prod: "/prod.yml" },
        templates: [{ path: "/app.conf.j2", component: "app", deployed_path: "/etc/app.conf", format: "space" }],
      } as never,
      { ...io, readFile: (p: string) => (files[p] ?? (p === "/dev.yml" ? "" : null)) } as never
    );
    return si.embedded ?? [];
  };

  it("names the test that decides a conditional row", () => {
    const extra = rows().find((e) => e.key === "Extra")!;
    expect(extra.instances?.map((i) => i.name)).toEqual(["prod"]);
    expect(extra.present_when).toEqual([{ variable: "some_flag" }]);
  });

  // A row every environment renders has nothing to explain, and naming a test
  // that changes nothing is noise.
  it("says nothing about a row whose presence does not vary", () => {
    expect(rows().find((e) => e.key === "Listen")!.present_when).toBeUndefined();
  });

  // The rule this module follows everywhere: report what was computed, claim
  // nothing about what was not.
  it("says nothing when the condition is one the evaluator does not read", () => {
    const odd = { ...FILES, "/app.conf.j2": "Listen {{ port }}\n{% if some_flag and port %}\nExtra on\n{% endif %}\n" };
    expect(rows(odd).find((e) => e.key === "Extra")).toBeUndefined();
  });
});
