// Equivalence test for the "ansible" recipe (src/recipes/ansible.ts): for each
// of the three ansible-* examples, the declarative build.yml pipeline
// (loadBuildSpec -> assembleFromSpecWithReport) must reproduce the example's
// committed input.json — which is what the hand-written build.ts produced
// before the recipe layer replaced it.
//
// The examples' input.json is git-ignored and regenerated by
// `cd examples/<n> && bun run ../../src/cli.ts import --spec review-sheet/build.yml -o input.json`,
// so it reflects the current source files rather than a stale snapshot; run
// that for each example before this test if the sources changed.
//
// Path convention note: `resolve` here returns paths relative to the example's
// own root (e.g. "roles/keycloak/defaults/main.yml") rather than the CLI's
// CWD-relative one — both are legitimate; this one is what makes a
// byte-for-byte comparison against the committed input.json possible.
// `readFile` accepts either form (root-relative from the recipe, or absolute
// from loadBuildSpec's own project/metadata_dirs/argument_specs resolution).

import { describe, it, expect, beforeEach } from "bun:test";
import { stubNonBuiltInProviders } from "./only-builtin-providers.js";
import { readFileSync } from "node:fs";
import { resolve as resolvePath, relative as relativePath, join, isAbsolute } from "node:path";
import { loadBuildSpec } from "../src/spec";
import "../src/recipes/index";
import { getRecipe, type RecipeIO } from "../src/recipe";
import { assembleFromSpecWithReport } from "../src/assemble-spec";
import type { Parameter } from "../src/types";

// The metadata provider registry is a process-wide singleton (see
// assemble.test.ts / spec.test.ts for the full rationale) — neutralize any
// non-core provider before each test so enrich()'s dictionary/argument-specs/
// project counts don't depend on cross-file test execution order.
beforeEach(stubNonBuiltInProviders);

const REPO_ROOT = resolvePath(__dirname, "..");

function makeReadFile(exampleRoot: string): (path: string) => string | null {
  return (p: string): string | null => {
    const abs = isAbsolute(p) ? p : join(exampleRoot, p);
    try {
      return readFileSync(abs, "utf-8");
    } catch {
      return null;
    }
  };
}

function buildActual(exampleName: string): ReturnType<typeof assembleFromSpecWithReport> {
  const exampleRoot = join(REPO_ROOT, "examples", exampleName);
  const specDir = join(exampleRoot, "review-sheet");
  const readFile = makeReadFile(exampleRoot);

  // Deliberately the exported library path (assemble-spec.ts), i.e. exactly
  // what `import --spec` runs — re-assembling the pipeline by hand here once
  // let a spec field (materialize) reach the CLI but not this test.
  return assembleFromSpecWithReport(loadBuildSpec(join(specDir, "build.yml"), { readFile }), {
    readFile,
    specDir,
    resolve: (p: string) => relativePath(exampleRoot, resolvePath(specDir, p)),
  });
}

function loadExpected(exampleName: string): unknown {
  const exampleRoot = join(REPO_ROOT, "examples", exampleName);
  return JSON.parse(readFileSync(join(exampleRoot, "input.json"), "utf-8"));
}

// A JSON round-trip normalizes both sides the same way (drops `undefined`
// properties, etc.) before the structural comparison.
function jsonRoundTrip(v: unknown): unknown {
  return JSON.parse(JSON.stringify(v));
}

function stripGeneratedAt(doc: unknown): unknown {
  const d = doc as { metadata?: { generated_at?: string } };
  if (d.metadata) delete d.metadata.generated_at;
  return doc;
}

type CategoryLike = { params?: Parameter[]; categories?: CategoryLike[] };

// Materialized rows are filed two levels deep — a parent "defaults" category,
// then a subcategory per dictionary group (see fileDrafts in assemble.ts) —
// so this recurses through `categories` instead of reading only the top level.
function paramsOf(cat: CategoryLike): Parameter[] {
  return [...(cat.params ?? []), ...(cat.categories ?? []).flatMap(paramsOf)];
}

function allParams(doc: unknown): Parameter[] {
  const d = doc as { sheets: { categories: CategoryLike[] }[] };
  return d.sheets.flatMap((s) => s.categories.flatMap(paramsOf));
}

function originCounts(params: Parameter[]): { common: number; overlay: number; embedded: number; default: number; out_of_scope: number } {
  const counts = { common: 0, overlay: 0, embedded: 0, default: 0, out_of_scope: 0 };
  for (const p of params) {
    if (p.origin === "common") counts.common++;
    else if (p.origin === "overlay") counts.overlay++;
    else if (p.origin === "embedded") counts.embedded++;
    else if (p.origin === "default") counts.default++;
    if (p.out_of_scope) counts.out_of_scope++;
  }
  return counts;
}

describe("ansible recipe: equivalence with the hand-written build.ts examples", () => {
  it("ansible-basic: nginx + postgresql", () => {
    const { input, report } = buildActual("ansible-basic");
    const actual = stripGeneratedAt(jsonRoundTrip(input));
    const expected = stripGeneratedAt(loadExpected("ansible-basic"));
    expect(actual).toEqual(expected);

    // 384 = 44 project-set params + 340 materialized default rows, every one of
    // the latter documented straight from the dictionary (which is what keeps
    // strict metadata passing for a full inventory nobody hand-authored). The
    // 341st is krb_server_keyfile, which sheet.yml marks out_of_scope — exempt
    // from enrichment as well as from strict.
    expect(report.filled).toBe(384);
    // project:9 is category placement, two remarks, and one out_of_scope.
    // pg_max_connections/pg_shared_buffers no longer need a project-metadata
    // override: the argument-specs provider now falls back from a row's
    // renamed key (max_connections/shared_buffers, the pg_settings directive)
    // to its ORIGINAL variable name (pg_max_connections/pg_shared_buffers)
    // when the key alone doesn't match (see providers/argument-specs.ts's
    // query.key-then-query.variable fallback, and metadata.ts's
    // MetadataQuery.variable) — S2's rename no longer strands that entry.
    // argument-specs:4 = the two descriptions (en) plus the two `type` fields
    // it also carries. Every other description still comes straight from the
    // nginx/postgresql dictionaries, so another project reviewing the same
    // products inherits them.
    expect(report.byProvider).toEqual({ dictionary: 1185, project: 9, "argument-specs": 4 });

    const counts = originCounts(allParams(actual));
    // 341 "default" rows: the postgresql sheet materializes pg_settings, so it
    // is the full inventory (22 set knobs + everything left at its default).
    expect(counts).toEqual({ common: 12, overlay: 16, embedded: 16, default: 341, out_of_scope: 1 });
  });

  it("ansible-httpd: httpd", () => {
    const { input, report } = buildActual("ansible-httpd");
    const actual = stripGeneratedAt(jsonRoundTrip(input));
    const expected = stripGeneratedAt(loadExpected("ansible-httpd"));
    expect(actual).toEqual(expected);

    // 19 = 18 + IfModule: httpd.ts now extracts <IfModule mpm_event_module>'s
    // module test as its own row (source = the opening tag), so it needs a
    // category and a description like every other directive here — both come
    // from the httpd@2.4 dictionary.
    expect(report.filled).toBe(19);
    // S2: every row is now named after its Apache directive (ServerTokens,
    // MaxRequestWorkers, ...), so meta/argument_specs.yml — which documents
    // httpd_server_tokens/httpd_max_request_workers by VARIABLE name — no
    // longer matches either row by `query.key` alone, but the provider falls
    // back to the row's ORIGINAL variable name (see providers/
    // argument-specs.ts's query.key-then-query.variable fallback), so it
    // still reaches both. project:1 is back down to just Include's category
    // placement (the two ServerTokens/MaxRequestWorkers description overrides
    // that used to live in sheet.yml are gone — argument_specs.yml is
    // reachable again, so nothing needed restating).
    expect(report.byProvider).toEqual({ dictionary: 91, project: 1, "argument-specs": 4 });

    const counts = originCounts(allParams(actual));
    // embedded: 3 = 2 + IfModule (a literal test in the template, like
    // Include/TypesConfig — not an Ansible variable).
    expect(counts).toEqual({ common: 10, overlay: 6, embedded: 3, default: 0, out_of_scope: 0 });
  });

  it("ansible-keycloak: server config + realm + clients, three sheets off one role", () => {
    const { input, report } = buildActual("ansible-keycloak");
    const actual = stripGeneratedAt(jsonRoundTrip(input));
    const expected = stripGeneratedAt(loadExpected("ansible-keycloak"));
    expect(actual).toEqual(expected);

    // 191 = the server sheet's 138 (18 keys the role sets + 121 materialized
    // rows, of 239 candidates — 118 carry no documented `default` and are
    // excluded by assemble.ts's materialize no-default gate — minus the one
    // the project marks out_of_scope, exempt from enrichment as from strict)
    // plus the realm sheet's 25 and the clients sheet's 28.
    expect(report.filled).toBe(191);
    // project:10 is every row Keycloak's admin console declines to name on its
    // own: the realm's four (each edited through a control writing SEVERAL
    // fields at once, so the extractor attributes that control's help text to
    // none of them) and the clients' equivalent, plus the `enabled` literals
    // the console shows as a header toggle rather than a form field, plus
    // `ifResourceExists`, which is a partial-import directive and not a
    // ClientRepresentation field at all. Everything else — all three sheets —
    // comes from the three extracted dictionaries.
    expect(report.byProvider).toEqual({ dictionary: 711, project: 10 });

    const server = input.sheets.find((s) => s.name === "keycloak configuration");
    const realm = input.sheets.find((s) => s.name === "keycloak realm");
    const clients = input.sheets.find((s) => s.name === "keycloak clients");
    expect(server && realm && clients).toBeTruthy();

    // The server dictionary is a real full extraction and the sheet is keyed by
    // the product's own config keys, so materializing (minus the no-default
    // exclusion above) makes it the exhaustive ledger of what Keycloak can be
    // configured with AND documented a real default for.
    expect(originCounts(allParams({ sheets: [server] }))).toEqual({
      common: 10,
      overlay: 7,
      embedded: 1,
      default: 121,
      out_of_scope: 1,
    });
    // The realm sheet is NOT materialized, and default: 0 is the assertion that
    // it stays that way. Its dictionary is `coverage: full` and would be
    // allowed to — but the words come from the admin console, which does not
    // expose every declared field as a form control, so expanding it produced
    // 42 rows the product describes nowhere and the strict gate rejected them.
    // See build.yml for the full reasoning.
    expect(originCounts(allParams({ sheets: [realm] }))).toEqual({
      common: 14,
      overlay: 10,
      embedded: 1,
      default: 0,
      out_of_scope: 0,
    });
    // Clients are a third sheet, not more rows on the realm one: five field
    // names exist in both RealmRepresentation and ClientRepresentation, so a
    // single sheet binding both dictionaries would make each of them
    // ambiguous. embedded: 3 = the two `protocol` literals (what makes each
    // client the thing it is) plus `ifResourceExists`.
    expect(originCounts(allParams({ sheets: [clients] }))).toEqual({
      common: 15,
      overlay: 10,
      embedded: 3,
      default: 0,
      out_of_scope: 0,
    });
  });
});

// The sheet's two paths: where the configuration LANDS (what an operator
// reviewing middleware parameters looks for) and the local file it is generated
// from (what verify/apply must act on). See src/types.ts's Sheet.file_path /
// source_file — the convention this recipe used backwards until now.
describe("ansible recipe: deployed_path", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": "nginx_port: 80\n",
    "/r/nginx.conf.j2": "listen {{ nginx_port }};\nsendfile on;\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: [],
  };
  const load = (extra: Record<string, string> = {}) => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "nginx", recipe: "ansible", defaults: "defaults.yml", template: "nginx.conf.j2", ...extra },
      io
    );
  };

  it("shows the deployed path and keeps the template as the source", () => {
    const si = load({ deployed_path: "/etc/nginx/nginx.conf" });
    expect(si.filePath).toBe("/etc/nginx/nginx.conf"); // verbatim: a path over there, not in the repo
    expect(si.sourceFile).toBe("/r/nginx.conf.j2");
  });

  it("falls back to the template as the displayed path when none is declared", () => {
    const si = load();
    expect(si.filePath).toBe("/r/nginx.conf.j2");
    expect(si.sourceFile).toBeUndefined();
  });

  it("refuses a deployed path with no template to render", () => {
    const recipe = getRecipe("ansible")!;
    expect(() =>
      recipe.load(
        { name: "nginx", recipe: "ansible", defaults: "defaults.yml", deployed_path: "/etc/nginx/nginx.conf" },
        io
      )
    ).toThrow(/no template/);
  });
});

// One group_vars file per host group, holding the variables of every role
// applied to it, is the ordinary Ansible layout — so a sheet built from ONE
// role's defaults sees the other roles' variables in its overlays and files
// them as its own parameters. The PoC hand-wrote 8 `out_of_scope` entries to
// suppress that, boilerplate growing with the number of sheets.
describe("ansible recipe: include/exclude key filters", () => {
  const files: Record<string, string> = {
    // The role's own defaults.
    "/r/defaults.yml": "httpd_port: 80\nhttpd_log_level: warn\n",
    // Shared group_vars: this role's variables plus two other roles'.
    "/r/group_vars.yml": "httpd_port: 8080\nkc_db_url: jdbc:postgresql://db/kc\nkcr_env: staging\nhttpd_only_here: on\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: ["staging"],
  };
  const load = (extra: Record<string, unknown> = {}) => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", overlays: { staging: "group_vars.yml" }, ...extra } as never,
      io
    );
  };
  const overlayKeys = (si: ReturnType<typeof load>) =>
    [...(si.layers.find((l) => l.kind === "overlay")!.entries.keys())];

  it("takes every overlay key by default — the behaviour a filter is opting out of", () => {
    expect(overlayKeys(load()).sort()).toEqual(["httpd_only_here", "httpd_port", "kc_db_url", "kcr_env"]);
  });

  it("drops the other roles' variables with exclude", () => {
    expect(overlayKeys(load({ exclude: ["kc_*", "kcr_*"] })).sort()).toEqual(["httpd_only_here", "httpd_port"]);
  });

  it("keeps only this role's variables with include", () => {
    expect(overlayKeys(load({ include: ["httpd_*"] })).sort()).toEqual(["httpd_only_here", "httpd_port"]);
  });

  it("keeps an overlay-only key that matches — a per-environment variable with no default is a legitimate row", () => {
    expect(overlayKeys(load({ include: ["httpd_*"] }))).toContain("httpd_only_here");
  });

  it("applies to the base layer too, so a filtered key is gone from the sheet entirely", () => {
    const si = load({ include: ["httpd_port"] });
    const base = si.layers.find((l) => l.kind === "base")!;
    expect([...base.entries.keys()]).toEqual(["httpd_port"]);
  });

  it("warns about a pattern that matched nothing", () => {
    const warnings: string[] = [];
    const original = console.warn;
    console.warn = (m: string) => warnings.push(m);
    try {
      load({ exclude: ["nope_*"] });
    } finally {
      console.warn = original;
    }
    expect(warnings.join("\n")).toContain("nope_*");
  });
});

// S1: a template variable that backs more than one directive (httpd's
// ProxyPass/ProxyPassReverse pair, both driven by the same backend variable)
// has no single product key to legitimately be — the observed bug was the
// LAST directive silently winning the row's name, dropping the other
// directive with no trace. See ansible.ts's module doc for the fix. S2: this
// derivation now runs for every templated sheet automatically, no `keying`
// flag to opt into it.
describe("ansible recipe: a variable used by more than one directive in the template", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": [
      "httpd_health_backend: http://127.0.0.1:9000",
      "httpd_proxy_backend: http://127.0.0.1:8080",
    ].join("\n"),
    // basename "httpd.conf" (after the .j2 strip) is unconditionally detected
    // as httpd by isHttpd(), so this needs no <Tag> block to be recognized.
    "/r/httpd.conf.j2": [
      'ProxyPass        "/health" "{{ httpd_health_backend }}/health"',
      'ProxyPassReverse "/health" "{{ httpd_health_backend }}/health"',
      'ProxyPass        "/"       "{{ httpd_proxy_backend }}/"',
      'ProxyPassReverse "/"       "{{ httpd_proxy_backend }}/"',
    ].join("\n"),
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: [],
  };
  const load = () => {
    const recipe = getRecipe("ansible");
    if (!recipe) throw new Error("ansible recipe is not registered");
    return recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", template: "httpd.conf.j2" },
      io
    );
  };

  it("files the N>1 variable under its own name, not the last directive it happened to touch", () => {
    const si = load();
    const base = si.layers.find((l): l is Extract<typeof si.layers[number], { kind: "base" }> => l.kind === "base")!;
    // httpd_health_backend backs both ProxyPass[0] and ProxyPassReverse[0] — no
    // single product key — so it must be keyed by the variable name itself,
    // never by either directive's key.
    expect(base.entries.has("httpd_health_backend")).toBe(true);
    expect(base.entries.has("ProxyPass[0]")).toBe(false);
    expect(base.entries.has("ProxyPassReverse[0]")).toBe(false);
    // httpd_proxy_backend is the same story for the second pair.
    expect(base.entries.has("httpd_proxy_backend")).toBe(true);
    expect(base.entries.has("ProxyPass[1]")).toBe(false);
    expect(base.entries.has("ProxyPassReverse[1]")).toBe(false);
  });

  it("does not add N>1 variables to keyMap — resolveKey's own fallback is what names the row after the variable", () => {
    const si = load();
    // No variable in this fixture backs exactly one directive, so keyMap ends
    // up empty and is omitted entirely (see ansible.ts) rather than kept as [].
    expect(si.keyMap).toBeUndefined();
  });

  it("reports every N>1 variable — never decides silently", () => {
    const warnings: string[] = [];
    const original = console.warn;
    console.warn = (m: string) => warnings.push(m);
    try {
      load();
    } finally {
      console.warn = original;
    }
    const joined = warnings.join("\n");
    expect(joined).toContain("httpd_health_backend");
    expect(joined).toContain("ProxyPass[0]");
    expect(joined).toContain("ProxyPassReverse[0]");
    expect(joined).toContain("httpd_proxy_backend");
    expect(joined).toContain("ProxyPass[1]");
    expect(joined).toContain("ProxyPassReverse[1]");
  });

  it("still keys a 1:1 variable by its product (directive) key as before", () => {
    const files1to1: Record<string, string> = {
      "/r/defaults.yml": "httpd_port: 8080\n",
      "/r/httpd.conf.j2": 'Listen "{{ httpd_port }}"\n',
    };
    const io1to1: RecipeIO = {
      readFile: (p: string) => files1to1[p] ?? null,
      specDir: "/r",
      resolve: (p: string) => `/r/${p.split("/").pop()}`,
      instances: [],
    };
    const recipe = getRecipe("ansible")!;
    const si = recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", template: "httpd.conf.j2" },
      io1to1
    );
    expect(si.keyMap).toEqual([{ boundKey: "Listen", variable: "httpd_port" }]);
  });
});

// S2: a `defaults` variable the template never resolves into a row (never
// referenced, or only tested in a Jinja `{% if %}`, like nginx's own
// nginx_gzip) must not be silently dropped just because "keying: bound" no
// longer exists to route it through the old "source"-only fallback. But it
// must only be RESCUED into the base map when it would otherwise be entirely
// invisible — a variable some overlay DOES set is already recovered by
// assemble.ts's own "keys seen only in overlays" sweep, with its true
// historical shape (a Pattern B row covering only the instances that set
// it); rescuing it here too would additionally fabricate a base value for
// every instance that never set it — a real behavior change, observed in the
// PoC's keycloak sheet (kc_bootstrap_admin_username/password, set only on
// `local`) before this distinction was added.
describe("ansible recipe: a defaults variable the template never resolves into a row", () => {
  const files: Record<string, string> = {
    "/r/defaults.yml": ["httpd_port: 8080", "httpd_gzip: true", "httpd_extra: fallback"].join("\n"),
    "/r/httpd.conf.j2": ['Listen "{{ httpd_port }}"', "{% if httpd_gzip %}", "gzip on;", "{% endif %}"].join("\n"),
    "/r/overlay.yml": "httpd_extra: staging-value\n",
  };
  const io: RecipeIO = {
    readFile: (p: string) => files[p] ?? null,
    specDir: "/r",
    resolve: (p: string) => `/r/${p.split("/").pop()}`,
    instances: ["staging"],
  };
  const load = () => {
    const recipe = getRecipe("ansible")!;
    return recipe.load(
      { name: "httpd", recipe: "ansible", defaults: "defaults.yml", template: "httpd.conf.j2", overlays: { staging: "overlay.yml" } },
      io
    );
  };

  it("rescues a variable no overlay ever sets into the base map, under its own name", () => {
    const si = load();
    const base = si.layers.find((l): l is Extract<typeof si.layers[number], { kind: "base" }> => l.kind === "base")!;
    expect(base.entries.has("httpd_gzip")).toBe(true);
    expect(base.entries.get("httpd_gzip")?.value).toBe("true");
  });

  it("does NOT rescue a variable some overlay sets — leaves it out of the base map entirely", () => {
    const si = load();
    const base = si.layers.find((l): l is Extract<typeof si.layers[number], { kind: "base" }> => l.kind === "base")!;
    // Left for assemble.ts's own overlay-only sweep to recover — see
    // buildDrafts in assemble.ts, which the equivalence test (assemble.test.ts)
    // covers for the resulting Pattern B shape.
    expect(base.entries.has("httpd_extra")).toBe(false);
  });
});
